### ISSUE TITLE
Problematic export of packages

### ISSUE THREAD

**Issue by eomasters-repos** [senbox-org/optical-toolbox#88]
When having a dependency to opttbx-s2msi-reader and to ceres-core the following error can occur:
```
java.lang.IllegalAccessError: class org.apache.commons.lang3.SystemUtils tried to access method 'org.apache.commons.lang3.JavaVersion org.apache.commons.lang3.JavaVersion.get(java.lang.String)' (org.apache.commons.lang3.SystemUtils is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @4a9526aa; org.apache.commons.lang3.JavaVersion is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @24e36ed7)
	at org.apache.commons.lang3.SystemUtils.<clinit>(SystemUtils.java:455)
	at eu.esa.opt.dataio.s2.S2ProductNamingUtils.processInputPath(S2ProductNamingUtils.java:380)
	at eu.esa.opt.dataio.s2.Sentinel2ProductReader.readProductNodesImpl(Sentinel2ProductReader.java:156)
	at org.esa.snap.core.dataio.AbstractProductReader.readProductNodes(AbstractProductReader.java:175)
	at org.esa.snap.core.dataio.ProductIO.readProduct(ProductIO.java:182)
```

Both modules export the package `org.apache.commons.lang3`
ceres core: `<publicPackage>org.apache.commons.lang3.*</publicPackage>`
opttbx-s2msi-reader: `<publicPackage>org.apache.commons.*</publicPackage>`

I think the reader should not export the commons packages this should be the duty of the ceres module.

**Comment by dianaharosa** [comment]
PR approved and merged
